
<?php echo $this->tag->form("item/create") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("item", "Go Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    <tr>
</table>

<?php echo $this->getContent(); ?>

<div align="center">
    <h1>Create item</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="name"><?= $item->getAttributeLabel('name') ?></label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("name", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="price"><?= $item->getAttributeLabel('price') ?></label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("price", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="type"><?= $item->getAttributeLabel('type') ?></label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("type", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="status"><?= $item->getAttributeLabel('status') ?></label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("status", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="description"><?= $item->getAttributeLabel('description') ?></label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("description", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="img"><?= $item->getAttributeLabel('img') ?></label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("img", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="public_range"><?= $item->getAttributeLabel('public_range') ?></label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("public_range", "type" => "number")) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Create") ?></td>
    </tr>
</table>

</form>
